-- begin TASKS_CARRIER
create unique index IDX_TASKS_CARRIER_UNIQ_NAME on TASKS_CARRIER (NAME) ^
-- end TASKS_CARRIER
-- begin TASKS_GOODS
create unique index IDX_TASKS_GOODS_UNIQ_NAME on TASKS_GOODS (NAME) ^
-- end TASKS_GOODS
-- begin TASKS_DELIVERY
alter table TASKS_DELIVERY add constraint FK_TASKS_DELIVERY_ON_GOODS foreign key (GOODS_ID) references TASKS_GOODS(ID)^
alter table TASKS_DELIVERY add constraint FK_TASKS_DELIVERY_ON_CARRIER foreign key (CARRIER_ID) references TASKS_CARRIER(ID)^
alter table TASKS_DELIVERY add constraint FK_TASKS_DELIVERY_ON_TRUCK foreign key (TRUCK_ID) references TASKS_TRUCK(ID)^
create unique index IDX_TASKS_DELIVERY_UNIQ_NUMBER_ on TASKS_DELIVERY (NUMBER_) ^
create index IDX_TASKS_DELIVERY_ON_GOODS on TASKS_DELIVERY (GOODS_ID)^
create index IDX_TASKS_DELIVERY_ON_CARRIER on TASKS_DELIVERY (CARRIER_ID)^
create index IDX_TASKS_DELIVERY_ON_TRUCK on TASKS_DELIVERY (TRUCK_ID)^
-- end TASKS_DELIVERY
-- begin TASKS_TRUCK_TYPE
create unique index IDX_TASKS_TRUCK_TYPE_UNIQ_NAME on TASKS_TRUCK_TYPE (NAME) ^
-- end TASKS_TRUCK_TYPE
-- begin TASKS_TRUCK
alter table TASKS_TRUCK add constraint FK_TASKS_TRUCK_ON_CARRIER foreign key (CARRIER_ID) references TASKS_CARRIER(ID)^
alter table TASKS_TRUCK add constraint FK_TASKS_TRUCK_ON_TRUCK_TYPE foreign key (TRUCK_TYPE_ID) references TASKS_TRUCK_TYPE(ID)^
create unique index IDX_TASKS_TRUCK_UNIQ_NUMBER_ on TASKS_TRUCK (NUMBER_) ^
create index IDX_TASKS_TRUCK_ON_CARRIER on TASKS_TRUCK (CARRIER_ID)^
create index IDX_TASKS_TRUCK_ON_TRUCK_TYPE on TASKS_TRUCK (TRUCK_TYPE_ID)^
-- end TASKS_TRUCK
-- begin TASKS_HISTORY_COST
alter table TASKS_HISTORY_COST add constraint FK_TASKS_HISTORY_COST_ON_CARRIER foreign key (CARRIER_ID) references TASKS_CARRIER(ID)^
create index IDX_TASKS_HISTORY_COST_ON_CARRIER on TASKS_HISTORY_COST (CARRIER_ID)^
-- end TASKS_HISTORY_COST
